# HW 1 Problem 7 

In [2]:
import numpy as np

### a)

In [7]:
Pa = np.array([[0,1],[1,0]])

In [8]:
da, va = np.linalg.eig(Pa)

In [37]:
np.round(da,3)

array([ 1., -1.])

In [32]:
np.round(va,3)

array([[ 0.707, -0.707],
       [ 0.707,  0.707]])

In [41]:
va_inv = np.linalg.inv(va)
np.round(va_inv,3)

array([[ 0.707,  0.707],
       [-0.707,  0.707]])

### b)

In [11]:
Pb = np.array([[0.0,1.0,0.0,0.0,0.0],
               [0.5,0.0,0.5,0.0,0.0],
               [0.0,0.5,0.0,0.5,0.0],
               [0.0,0.0,0.5,0.0,0.5],
               [0.0,0.0,0.0,1.0,0.0]])

In [12]:
db, vb = np.linalg.eig(Pb)

In [36]:
np.round(db,3)

array([-1.   , -0.707, -0.   ,  1.   ,  0.707])

In [31]:
np.round(vb,3)

array([[ 0.447,  0.577,  0.577,  0.447, -0.577],
       [-0.447, -0.408, -0.   ,  0.447, -0.408],
       [ 0.447,  0.   , -0.577,  0.447, -0.   ],
       [-0.447,  0.408, -0.   ,  0.447,  0.408],
       [ 0.447, -0.577,  0.577,  0.447,  0.577]])

In [40]:
vb_inv = np.linalg.inv(vb)
np.round(vb_inv,3)

array([[ 0.28 , -0.559,  0.559, -0.559,  0.28 ],
       [ 0.433, -0.612,  0.   ,  0.612, -0.433],
       [ 0.433, -0.   , -0.866, -0.   ,  0.433],
       [ 0.28 ,  0.559,  0.559,  0.559,  0.28 ],
       [-0.433, -0.612, -0.   ,  0.612,  0.433]])

### c)

In [15]:
Pc = np.array([[1.0,0.0,0.0],
               [0.5,0.0,0.5],
               [0.0,0.0,1.0]])

In [16]:
dc, vc = np.linalg.eig(Pc)

In [35]:
np.round(dc,3)

array([0., 1., 1.])

In [30]:
np.round(vc,3)

array([[0.   , 0.894, 0.   ],
       [1.   , 0.447, 0.447],
       [0.   , 0.   , 0.894]])

In [42]:
vc_inv = np.linalg.inv(vc)
np.round(vc_inv,3)

array([[-0.5  ,  1.   , -0.5  ],
       [ 1.118,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  1.118]])

### d)

In [19]:
Pd = np.array([[1.0,0.0,0.0,0.0,0.0],
               [0.5,0.0,0.5,0.0,0.0],
               [0.0,0.5,0.0,0.5,0.0],
               [0.0,0.0,0.5,0.0,0.5],
               [0.0,0.0,0.0,0.0,1.0]])

In [20]:
dd, vd = np.linalg.eig(Pd)

In [34]:
np.round(dd,3)

array([-0.707,  0.   ,  0.707,  1.   ,  1.   ])

In [28]:
np.round(vd,3)

array([[ 0.   ,  0.   ,  0.   ,  0.73 ,  0.   ],
       [ 0.5  ,  0.707, -0.5  ,  0.548,  0.183],
       [-0.707, -0.   , -0.707,  0.365,  0.365],
       [ 0.5  , -0.707, -0.5  ,  0.183,  0.548],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.73 ]])

In [43]:
vd_inv = np.linalg.inv(vd)
np.round(vd_inv,3)

array([[-0.146,  0.5  , -0.707,  0.5  , -0.146],
       [-0.354,  0.707, -0.   , -0.707,  0.354],
       [ 0.854, -0.5  , -0.707, -0.5  ,  0.854],
       [ 1.369,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  1.369]])

### e)

In [23]:
Pd = np.array([[1/2,1/2,0.0,0.0,0.0],
               [1/6,5/6,0.0,0.0,0.0],
               [0.0,0.0,3/4,1/4,0.0],
               [0.0,0.0,1/8,2/3,5/24],
               [0.0,0.0,0.0,1/6,5/6]])

In [24]:
de, ve = np.linalg.eig(Pd)

In [33]:
np.round(de,3)

array([0.333, 1.   , 0.464, 0.786, 1.   ])

In [29]:
np.round(ve,3)

array([[-0.949, -0.707,  0.   ,  0.   ,  0.   ],
       [ 0.316, -0.707,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.623,  0.881,  0.577],
       [ 0.   ,  0.   , -0.713,  0.128,  0.577],
       [ 0.   ,  0.   ,  0.322, -0.455,  0.577]])

In [44]:
ve_inv = np.linalg.inv(ve)
np.round(ve_inv,3)

array([[-0.791,  0.791, -0.   , -0.   , -0.   ],
       [-0.354, -1.061, -0.   , -0.   , -0.   ],
       [-0.   , -0.   ,  0.374, -0.857,  0.483],
       [ 0.   ,  0.   ,  0.664,  0.193, -0.857],
       [ 0.   ,  0.   ,  0.315,  0.63 ,  0.787]])